sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
service:
  - mongodb
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install --upgrade pip coveralls pytest-cov
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install subprocess32; fi
  - pip install -r requirements.txt --allow-external --cache-dir=$HOME/.pip-cache .
script: python setup.py test
after_success:
  - coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.org#hackerfleet"
    on_success: change
    use_notice: true
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} ( %{duration}, %{build_url} )"
  email:
    recipients:
        - riot@c-base.org
    on_success: change

