sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install --upgrade pip coveralls pytest-cov pytest
  - python setup.py install
  - pip install -r requirements.txt --allow-external --cache-dir=$HOME/.pip-cache .
script: python setup.py test
after_success:
  - coveralls
notifications:
  irc: "chat.freenode.org#hackerfleet"
