language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt --allow-external --cache-dir=$HOME/.pip-cache .
  - python setup.py install
script: python setup.py test
