language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
cache:
  directories:
    - $HOME/.pip-cache/
install: 
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache .
script: python setup.py test
